import path from "path";
import fs from "fs";
import React from "react";
import ReactDOMServer from "react-dom/server";
import express from "express";

import config from "./config";
import {App} from "../src/App";
import {myMizuClient} from "./myMizuClient";
import i18nConfig from "../src/i18nConfig";
import {buildRobotsTxt, getSitemap, isSitemapConfigured} from "./sitemap";

const PORT = process.env.PORT || 3000;
const gmapApiKey = config.gmApiKey;
const gaTag = config.gaTag;
const app = express();
const crypto = require('crypto');

const getLanguage = (req) => {
  const lang = req.acceptsLanguages("en", "ja");
  if (lang) {
    return lang;
  }
  return "en";
};


const getToken = (req) => {
  if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
    return req.headers.authorization.split(' ')[1];
  } else if (req.query && req.query.token) {
    return req.query.token;
  }
  return null;
};


// Every asset was previously served with Express's default
// `Cache-Control: public, max-age=0`, so each repeat visit spent a revalidation
// round trip per asset. On mobile latency that is a large share of a repeat
// view. The bundle is now addressed by content hash so it can be cached hard
// and still change instantly on deploy.
const DIST_BUNDLE = path.join(__dirname, "../dist/bundle.js");
const HASHED_BUNDLE_RE = /^\/bundle\.[0-9a-f]{12}\.js$/;

let bundleHash = null;
const getBundleHash = () => {
  if (bundleHash) return bundleHash;
  try {
    bundleHash = crypto
      .createHash("sha256")
      .update(fs.readFileSync(DIST_BUNDLE))
      .digest("hex")
      .slice(0, 12);
  } catch (e) {
    // Server started before the client build finished. Fall back to the
    // unhashed URL rather than failing the page.
    console.warn("Could not hash bundle.js; serving it unhashed:", e.message);
    bundleHash = null;
  }
  return bundleHash;
};

const bundleUrl = () => {
  const hash = getBundleHash();
  return hash ? `/bundle.${hash}.js` : "/bundle.js";
};

// Content-addressed: the URL changes whenever the bundle does, so this can be
// cached indefinitely.
app.get(HASHED_BUNDLE_RE, (req, res) => {
  res.set("Cache-Control", "public, max-age=31536000, immutable");
  res.sendFile(DIST_BUNDLE);
});

// Kept for any client holding the old URL, and as the fallback when hashing
// failed. Must revalidate, since this path's contents change on every deploy.
app.get("/bundle.js", (req, res) => {
  res.set("Cache-Control", "public, max-age=0, must-revalidate");
  res.sendFile(DIST_BUNDLE);
});

app.use(
  "/public",
  express.static(path.join(__dirname, "../public"), {
    etag: true,
    lastModified: true,
    setHeaders: (res, filePath) => {
      // Images and fonts are replaced in place occasionally (the cooling
      // shelter pins were), so a week rather than a year: long enough to skip
      // the revalidation round trips, short enough that a swapped-in asset
      // still lands without a rename.
      const longLived = /\.(png|jpe?g|gif|svg|webp|ico|woff2?|ttf|eot)$/i;
      res.setHeader(
        "Cache-Control",
        longLived.test(filePath)
          ? "public, max-age=604800"
          : "public, max-age=3600"
      );
    },
  })
);

app.get("/.well-known/apple-app-site-association", (req, res) => {
  res.type("application/json");
  res.sendFile(
    path.join(__dirname, "../public/.well-known/apple-app-site-association")
  );
});

app.get("/.well-known/assetlinks.json", (req, res) => {
  res.type("application/json");
  res.sendFile(path.join(__dirname, "../public/.well-known/assetlinks.json"));
});

// --- SEO: robots + sitemaps -------------------------------------------------
// These must live at the site root. Static assets are mounted under /public, so
// a file dropped in public/ would only be reachable at /public/robots.txt, which
// no crawler looks for.
//
// The sitemap itself is generated by the API (php artisan mymizu:generate-sitemap)
// and uploaded to the cloud disk; we proxy it so it is served from the same
// origin as the URLs it lists. Point SITEMAP_SOURCE at that bucket path.

app.get("/robots.txt", (req, res) => {
  res.type("text/plain");
  res.set("Cache-Control", "public, max-age=86400");
  res.send(buildRobotsTxt());
});

const sendSitemap = async (res, name) => {
  if (!isSitemapConfigured()) {
    console.error("SITEMAP_SOURCE is not set; cannot serve", name);
    return res.status(503).type("text/plain").send("Sitemap not configured");
  }

  try {
    const body = await getSitemap(name);
    res.type("application/xml");
    res.set("Cache-Control", "public, max-age=3600");
    return res.send(body);
  } catch (error) {
    if (error.notFound) {
      return res.status(404).type("text/plain").send("Not found");
    }
    console.error(`Unable to serve ${name}:`, error.message);
    res.set("Retry-After", "600");
    return res
      .status(503)
      .type("text/plain")
      .send("Sitemap temporarily unavailable");
  }
};

app.get("/sitemap.xml", (req, res) => sendSitemap(res, "sitemap.xml"));

app.get("/sitemap-spots-:page.xml", (req, res) =>
  sendSitemap(res, `sitemap-spots-${req.params.page}.xml`),
);
// --- end SEO ----------------------------------------------------------------


app.get("/api/authorize", async (req, res) => {
  const params = {
    l: getLanguage(req),
    platform: 'web',
    client_version: '1.0',
    client_build: '100',
    uuid: crypto.randomUUID(),
  };

  try {
    const token = await myMizuClient(null, null).get("/api/start", params);

    res.status(200).send(token);
  } catch (e) {
    res.status(400).json({
      message: "Unable to complete authorization",
      error: e,
    });
  }
});

const INITIAL_POSITION = {
  c1: 35.662,
  c2: 39.73655447363853,
  c3: 32.64245244856602,
  c4: 150.75432142615318,
};

const TAP_FETCH_OPTIONS = {
  include_cooling_shelters: true,
};

app.get("/get-initial-markers", async (req, res) => {
  try {
    const markers = await myMizuClient(getToken(req), getLanguage(req)).get("/api/taps/nearby", {
      ...INITIAL_POSITION,
      ...TAP_FETCH_OPTIONS,
    });

    res.status(200).send(markers);
  } catch (e) {
    res.status(400).json({
      message: "Unable to fetch initial markers",
      error: e,
    });
  }
});

app.get("/community", async (req, res) => {
  try {
    const data = await myMizuClient(getToken(req), getLanguage(req)).get("/api/community");
    res.status(200).send(data);
  } catch (error) {
    res.status(400).json({
      message: "Unable to fetch community",
      error,
    });
  }
});

app.get("/get-marker-moving-map?", async (req, res) => {
  try {
    const {c1, c2, c3, c4} = req.query;

    const pos = {
      c1,
      c2,
      c3,
      c4,
    };

    const markers = await myMizuClient(getToken(req), getLanguage(req)).get("/api/taps/nearby", {
      ...pos,
      ...TAP_FETCH_OPTIONS,
    });

    res.status(200).send(markers);
  } catch (e) {
    res.status(400).json({
      message: "Unable to fetch initial markers",
      error: e,
    });
  }
});

// Feature: Not working yet, error on server side, but we can use this to fetch all clusters and cache them on the client side
app.get("/get-clusters", async (req, res) => {
  try {
    const ifNoneMatch = req.headers["if-none-match"];

    const upstream = await myMizuClient(getToken(req), getLanguage(req)).getRaw(
      "/api/taps/clusters/all",
      {},
      {
        headers: ifNoneMatch ? { "If-None-Match": ifNoneMatch } : {},
        validateStatus: (status) => status === 200 || status === 304,
      }
    );

    if (upstream.headers["etag"]) {
      res.set("ETag", upstream.headers["etag"]);
    }
    res.set(
      "Cache-Control",
      upstream.headers["cache-control"] || "public, max-age=3600"
    );

    if (upstream.status === 304) {
      res.status(304).end();
      return;
    }

    res.set("Content-Type", "application/json");
    res.status(200).send(upstream.data);
  } catch (e) {
    const status = e.response?.status || 502;
    const upstreamBody = e.response?.data;

    res.status(status).json({
      message: "Unable to fetch clusters",
      error: upstreamBody ?? e.message,
    });
  }
});

//*

app.get("/get-refill-spot/:slug", async (req, res) => {
  try {
    const info = await myMizuClient(getToken(req), getLanguage(req)).get(`/api/taps/${req.params.slug}/`);
    res.status(200).send(info);
  } catch (e) {
    res.status(400).json({
      message: "Unable to fetch refill spot",
      error: e,
    });
  }
});

// Both HTML routes render the same shell; this is the shared implementation the
// duplicated copies used to ask for in a TODO. It also rewrites the bundle tag
// to the content-hashed URL so the immutable caching above actually applies.
const renderPage = (res) => {
  fs.readFile(path.resolve("./public/index.html"), "utf8", (err, data) => {
    if (err) {
      console.error(err);
      return res.status(500).send("An error occurred");
    }

    const html = data
      .replace('src="/bundle.js"', `src="${bundleUrl()}"`)
      .replace(
        '<div id="root"></div>',
        `
        <script>window.__GM_API_KEY__=${JSON.stringify(gmapApiKey)}</script>
        <script>window.__GA_TAG__=${JSON.stringify(gaTag)}</script>
        <div id="root">${ReactDOMServer.renderToString(
          <App gmApiKey={gmapApiKey} gaTag={gaTag} />
        )}</div>
        `
      )
      .replace(
        '<div id="ga"></div>',
        `
        <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=${gaTag}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){window.dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '${gaTag}');
</script>
        `
      );

    // The document embeds the hashed bundle URL, so it must not be cached past
    // a deploy or clients would keep asking for a bundle that no longer exists.
    res.set("Cache-Control", "private, no-cache");
    return res.send(html);
  });
};

app.get("/refill/:language/:slug", (req, res) => renderPage(res));

app.get("/", (req, res) => renderPage(res));

app.listen(PORT, () => {
  console.log(`Server is listening on port ${PORT}`);
});
